import streamlit as st

if "user_id" not in st.session_state:
    st.switch_page("welcome.py")

# st.title("Freesound search questionnaire", anchor=False)
st.title("Thank you for participating!", anchor=False)

st.write("Thank you for participating in this questionnaire!")
st.write("You can now close this tab.")
st.write("Have a great day!")
st.write("🎉")
st.write("👋")
st.write("🔊")
st.write("🎶")
st.write("🎧")
st.write("🎵")
st.write("🔎")
st.write("🤔")
st.write("🤗")
st.write("🙏")
st.write("👍")
st.write("👏")
st.write("👌")
st.write("👀")
st.write("🔥")
st.write("🚀")
st.write("🌟")
st.write("🌈")
st.write("🎈")
st.write("Are you still reading this?")
st.write("🤯")
st.write("🤩")
st.write("🥳")
st.markdown("Please feel free to share this survey with your friends and colleagues!")
